name: persian_number_utility
description: A Flutter Package for convert number to English or Persian (Farsi) letter
version: 0.1.5
author: Mehdi Nemati <mhDx92@gmail.com>
homepage: https://github.com/mehdi-nemati/persian_number_utility

environment:
  sdk: ">=2.1.0 <3.0.0"