name: persian_number_utility
description: A Flutter Package for convert number to English or Persian (Farsi) letter
version: 0.2.0
homepage: https://github.com/mehdi-nemati/persian_number_utility

environment:
  sdk: ">=2.6.0 <3.0.0"